name: Build the project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checking out
        uses: actions/checkout@v4

      - name: Setting up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Building with Maven
        run: mvn clean package
