name: Release a new version

on:
  pull_request:
  push:
    paths:
      - 'pom.xml'

permissions:
  contents: write
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checking out
        uses: actions/checkout@v4

      - name: Setting up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - id: version-decider
        name: Version Decider
        uses: thiagodnf/version-decider@main
        with:
          file: ./pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - if: steps.version-decider.outputs.new
#        name: Get previous tag
#        id: get_prev_tag
#        run: |
#          git fetch --tags
#          PREV_TAG=$(git describe --tags --abbrev=0 --always)
#          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
#
#      - if: steps.version-decider.outputs.new
#        name: Generate changelog
#        id: changelog
#        run: |
#          LOG=$(git log ${{ steps.get_prev_tag.outputs.prev_tag }}..HEAD --pretty=format:"- %s")
#          echo "$LOG" > release_notes.md
#          cat release_notes.md

      - if: steps.version-decider.outputs.new
        name: Publish package to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.version-decider.outputs.new
        name: Creating a new release on Github
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.version-decider.outputs.version }}
          tag_name: v${{ steps.version-decider.outputs.version }}
#          body_path: release_notes.md
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


